In [1]:
from tensorflow.keras.preprocessing.text import one_hot 

RuntimeError: module was compiled against NumPy C-API version 0x10 (NumPy 1.23) but the running NumPy has C-API version 0xf. Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem.

In [2]:
# Sentences
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good girl',
      'I am a good developer',
      'Understand the meaning of words',
      'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good girl',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size=10000

In [5]:
# One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9715, 9824, 3112, 9868],
 [9715, 9824, 3112, 6988],
 [9715, 3134, 3112, 1545],
 [6466, 7302, 1421, 3926, 3711],
 [6466, 7302, 1421, 3926, 3372],
 [4254, 9715, 7165, 3112, 3219],
 [9621, 6772, 9450, 3926]]

In [6]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
print(np.__version__)

1.22.4


In [8]:
pip install numpy==1.23.0

  Using cached numpy-1.23.0-cp39-cp39-win_amd64.whl.metadata (2.2 kB)
Using cached numpy-1.23.0-cp39-cp39-win_amd64.whl (14.7 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
  Rolling back uninstall of numpy
  Moving to c:\users\hp\appdata\roaming\python\python39\scripts\f2py.exe
   from C:\Users\HP\AppData\Local\Temp\pip-uninstall-tnx4elio\f2py.exe
  Moving to c:\users\hp\appdata\roaming\python\python39\site-packages\numpy-1.22.4.dist-info\
   from C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\~umpy-1.22.4.dist-info
  Moving to c:\users\hp\appdata\roaming\python\python39\site-packages\numpy\
   from C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\~umpy
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\ProgramData\\Anaconda3\\envs\\clean_env\\Lib\\site-packages\\numpy\\__config__.py'
Consider using the `--user` option or check the permissions.



In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9715 9824 3112 9868]
 [   0    0    0    0 9715 9824 3112 6988]
 [   0    0    0    0 9715 3134 3112 1545]
 [   0    0    0 6466 7302 1421 3926 3711]
 [   0    0    0 6466 7302 1421 3926 3372]
 [   0    0    0 4254 9715 7165 3112 3219]
 [   0    0    0    0 9621 6772 9450 3926]]


In [11]:
# Feature Representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\ProgramData\Anaconda3\envs\clean_env\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step


array([[[-1.06665604e-02,  7.66883045e-03,  1.71587951e-02,
          9.29434225e-03, -2.46124025e-02,  4.77636717e-02,
         -3.70940343e-02,  4.28970195e-02,  1.26508623e-03,
          4.12676595e-02],
        [-1.06665604e-02,  7.66883045e-03,  1.71587951e-02,
          9.29434225e-03, -2.46124025e-02,  4.77636717e-02,
         -3.70940343e-02,  4.28970195e-02,  1.26508623e-03,
          4.12676595e-02],
        [-1.06665604e-02,  7.66883045e-03,  1.71587951e-02,
          9.29434225e-03, -2.46124025e-02,  4.77636717e-02,
         -3.70940343e-02,  4.28970195e-02,  1.26508623e-03,
          4.12676595e-02],
        [-1.06665604e-02,  7.66883045e-03,  1.71587951e-02,
          9.29434225e-03, -2.46124025e-02,  4.77636717e-02,
         -3.70940343e-02,  4.28970195e-02,  1.26508623e-03,
          4.12676595e-02],
        [-3.74022126e-02,  4.56348062e-05,  1.13651529e-02,
         -2.79394034e-02,  3.47833969e-02,  2.19847821e-02,
          1.76644661e-02, -2.54093651e-02,  1.208316

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9715, 9824, 3112, 9868])

In [16]:
embedded_docs = np.array([[0,0,0,0,6057, 6050, 3432,  923]])
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
[[[-0.01066656  0.00766883  0.0171588   0.00929434 -0.0246124
    0.04776367 -0.03709403  0.04289702  0.00126509  0.04126766]
  [-0.01066656  0.00766883  0.0171588   0.00929434 -0.0246124
    0.04776367 -0.03709403  0.04289702  0.00126509  0.04126766]
  [-0.01066656  0.00766883  0.0171588   0.00929434 -0.0246124
    0.04776367 -0.03709403  0.04289702  0.00126509  0.04126766]
  [-0.01066656  0.00766883  0.0171588   0.00929434 -0.0246124
    0.04776367 -0.03709403  0.04289702  0.00126509  0.04126766]
  [ 0.02400381 -0.03332794  0.02202721  0.02959469 -0.00759415
    0.01566306  0.01206418 -0.00447742 -0.00646311  0.00643973]
  [ 0.0490733  -0.02715178  0.03114516 -0.00464724  0.01411916
    0.00416864 -0.04466663 -0.00926648  0.0448921  -0.01812283]
  [ 0.04510944  0.00590315 -0.04994234 -0.04174323  0.01597517
    0.01952269  0.01040673  0.01893045 -0.01168178  0.01025803]
  [ 0.03052742 -0.01081253  0.01781354  0.03832148  0.00858251
    0.02910382